services:
  app:
    container_name: inventory
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app-network
  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
